# Basic
title: Edward Zh
subtitle: å¥½å¥‡å¿ƒ | ç ä»£ç  | æŒ‰å¿«é—¨ | ç©· | Apple | è½¯ç‹— | +1s
description: >
  ä¸€ä¸ªæ™®é€šçš„ç¨‹åºå‘˜ / å–œæ¬¢ç²¤è¯­æ­Œ
avatar: //img.edzh.me/543885dc0eb03677db6993d8c2a4cf78.jpg
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: obesitychow
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: iOS / Android / J2EE
url: "https://edzh.me"

backgroundImage: //pic.edzh.me/fb6d28514af2b9dd5e2598a691e058a3.jpg?imageView2/0/w/2160
# # Comment
# comment:
#     # disqus: leopard
#     duoshuo:

# Social
social:
    # weibo: edchow
    github: ObesityChow
    # twitter:
    mail: i@edzh.me

# ç™¾åº¦ç»Ÿè®¡
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
# baidu:
#     id: 270de8acf10360fbf9e1d38427dd72ba

# # Google Analytics
# # ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
# ga:
#     id: UA-84134159-3
#     host: auto


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}


#å‹æƒ…é“¾æ¥
flink:
    - {title: Neuron Black's Blog, description: Neuron Blackçš„åšå®¢, url: 'http://neuronblack.cc'}
    - {title: Jason's Blog, description: JasonelChen - Tencent, url: 'https://blog.ijason.cc/'}

beian: è‹ICPå¤‡16015250å·

# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"
